# Generated by Django 3.1.4 on 2021-01-22 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_auto_20210103_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='Related_comment_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
