# Generated by Django 3.1.4 on 2021-01-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
