# Generated by Django 3.1.4 on 2021-01-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comment_unliked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['answer_date']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unliked',
        ),
    ]
