# Generated by Django 3.1.4 on 2021-01-27 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0010_auto_20210127_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.ManyToManyField(related_name='sds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(related_name='ds', to=settings.AUTH_USER_MODEL),
        ),
    ]
