# Generated by Django 3.1.4 on 2021-02-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20210201_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment2',
        ),
    ]
