# Generated by Django 3.1.4 on 2021-11-30 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0022_article_readlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='clapNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='clapUser',
            field=models.ManyToManyField(blank=True, related_name='Makaleyi_alkislayan_kullanicilar', to=settings.AUTH_USER_MODEL),
        ),
    ]
