# Generated by Django 3.1.4 on 2021-01-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.jpg ', upload_to='profile/', verbose_name='Kullanıcı fotografı '),
        ),
    ]
