# Generated by Django 3.1.4 on 2021-01-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210128_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='profile/', verbose_name='Kullanıcı fotografı '),
        ),
    ]
