# Generated by Django 3.1.4 on 2021-11-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211126_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='readList',
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
