# Generated by Django 3.1.4 on 2021-11-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211127_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitterAdress',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
